### ISSUE TITLE
ENS registration on more networks

### ISSUE THREAD

**Issue by individualpirate** [MyCryptoHQ/ens-validation#10]
Hello,

I have registered freemoonfaucet.xyz on Ethereum and Ropsten, but I plan to use it on another network (Fusion), and when visiting the site with Metamask (mobile version) when logged into Fusion it won't recognise that it has ENS validation, unless you come in while logged into Etherum (or Ropsten) I guess.

I tried if it'd be possible to also register the site on Fusion, but get the following error:

{"graphQLErrors":[],"networkError":{"reason":"underlying network changed","code":"NETWORK_ERROR","event":"changed","network":{"name":"homestead","chainId":1,"ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"},"detectedNetwork":{"chainId":32659,"name":"unknown"}},"message":"Network error: underlying network changed (event=\"changed\", network={\"name\":\"homestead\",\"chainId\":1,\"ensAddress\":\"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e\"}, detectedNetwork={\"chainId\":32659,\"name\":\"unknown\"}, code=NETWORK_ERROR, version=providers/5.4.1)"}

If it's not too much to ask, could you enable registration on any network?

**Comment by Arachnid** [comment]
ENS is only available on mainnet - though  you can associate addresses of any blockchain with your name there.
